#More Mobs
version: 1.0

#Zombie Mobs

zombierider: true
zombieminer: true
zombiejungle: true
zombievariety: true


#Skeleton Mobs
skeletonrider: true
skeletonminer: true
skeletonjungle: true


#Drowned
drownedswamp: true
drownedvariety: true
